redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "M:\\Claude\\zedexams.com\\.claude\\worktrees\\great-almeida-858cda\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "M:\\Claude\\zedexams.com\\.claude\\worktrees\\great-almeida-858cda"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/ai/chat"
to = "https://us-central1-examsprepzambia.cloudfunctions.net/apiAiChat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/payments/momo/initiate"
to = "https://us-central1-examsprepzambia.cloudfunctions.net/apiCreateMomoPayment"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/payments/momo/status"
to = "https://us-central1-examsprepzambia.cloudfunctions.net/apiMomoPaymentStatus"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]