export const LESSON_FIRESTORE_SCHEMA = {
  collection: 'lessons',
  document: {
    schemaVersion: 'number',
    title: 'string',
    grade: "'4' | '5' | '6'",
    subject: 'string',
    term: "'1' | '2' | '3'",
    topic: 'string',
    creationMode: "'slide-builder' | 'quick-lesson' | 'imported_pptx' | 'pptx_viewer'",
    mode: "'slide-builder' | 'quick-lesson' | 'imported_pptx' | 'pptx_viewer'",
    sourceFileName: 'string',
    assetBatchId: 'string',
    importStatus: "'success' | 'needs_review' | ''",
    presentation: {
      sourceFileName: 'string',
      sourcePath: 'string',
      sourceUrl: 'string',
      sourceContentType: 'string',
      sourceSize: 'number',
      viewerType: "'slide_images' | 'office_embed' | ''",
      conversionStatus: "'ready' | 'needs_review' | 'failed' | ''",
      slideCount: 'number',
      slideImages: [
        {
          id: 'string',
          order: 'number',
          imageUrl: 'string',
          storagePath: 'string',
          contentType: 'string',
          extension: 'string',
          width: 'number',
          height: 'number',
          alt: 'string',
        },
      ],
      conversionWarnings: 'string[]',
    },
    theme: 'string',
    slides: [
      {
        id: 'string',
        order: 'number',
        type: "'title' | 'text' | 'bullets' | 'imageText' | 'example' | 'question' | 'summary' | 'end'",
        title: 'string',
        subtitle: 'string',
        body: 'string',
        bullets: 'string[]',
        imageUrl: 'string',
        imageAlt: 'string',
        imageStoragePath: 'string',
        imageSourcePath: 'string',
        importAssetId: 'string',
        example: 'string',
        prompt: 'string',
        answer: 'string',
        explanation: 'string',
        teacherNotes: 'string',
        requiresReview: 'boolean',
        reviewNotes: 'string[]',
        importWarnings: 'string[]',
        sourceSlidePath: 'string',
      },
    ],
    activities: [
      {
        id: 'string',
        slideId: 'string',
        slideTitle: 'string',
        prompt: 'string',
        order: 'number',
      },
    ],
    answers: [
      {
        id: 'string',
        slideId: 'string',
        slideTitle: 'string',
        prompt: 'string',
        answer: 'string',
        explanation: 'string',
        order: 'number',
      },
    ],
    linkedQuizId: 'string',
    linkedActivities: 'string[]',
    isPublished: 'boolean',
    status: "'draft' | 'pending' | 'published' | 'rejected'",
    createdBy: 'uid',
    createdAt: 'serverTimestamp',
    updatedAt: 'serverTimestamp',
    submittedAt: 'serverTimestamp | null',
    approvedBy: 'uid | null',
    approvedAt: 'serverTimestamp | null',
  },
}
